receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include:
      - /app/logs/*.log
    start_at: beginning
    storage: null
    retry_on_failure:
      enabled: true
    operators: []

processors:
  batch:
    send_batch_size: 1024
    timeout: 1s
    send_batch_max_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 500
    spike_limit_mib: 100
  
  resource:
    attributes:
      - key: service.name
        value: ${env:SERVICE_NAME:-unknown-service}
        action: upsert
      - key: deployment.environment
        value: ${env:ENVIRONMENT:-development}
        action: upsert
      - key: service.namespace
        value: vaultsearch
        action: upsert

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    logs:
      level: info
      development: false
      disable_caller: false
      disable_stacktrace: false
      sampling:
        initial: 2
        thereafter: 500
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp/jaeger, debug]
    logs:
      receivers: [filelog]
      processors: [memory_limiter, batch, resource]
      exporters: [debug]
