server:
  port: 8081

spring:
  application:
    name: upload-download-service
  cloud:
    aws:
      region:
        static: us-east-1

aws:
  region: us-east-1
  s3:
    bucket-name: vaultsearch-uploads
  dynamodb:
    table-name: vaultsearch-metadata
  sqs:
    queue-name: vaultsearch-queue
    queue-url: https://sqs.us-east-1.amazonaws.com/159014723710/vaultsearch-queue

logging:
  file:
    name: logs/vaultsearch-upload.log
  level:
    com.vaultsearch: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0   # Sample 100% of requests for development
    propagation:
      type: W3C
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces   # OTEL Collector HTTP endpoint
      protocol: http/protobuf

otel:
  resource:
    attributes: service.name=upload-download-service
    service:
      name: ${spring.application.name}
