api.http.host: 0.0.0.0
api.http.port: 9600
log.format: json
log.level: info
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
pipeline.batch.delay: 50
pipeline.batch.size: 125
pipeline.workers: 2
queue.max_bytes: 1gb
queue.type: memory
slowlog.threshold.debug: 200ms
slowlog.threshold.info: 500ms
slowlog.threshold.trace: 100ms
slowlog.threshold.warn: 1s
xpack.management.enabled: false
xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED}
